export const LOCALE_CHANGE = 'LOCALE_CHANGE';

export const DATE_STYLE_CHANGE = 'DATE_STYLE_CHANGE';

export const TIME_STYLE_CHANGE = 'TIME_STYLE_CHANGE';

export const LOCALE_MATCHER_CHANGE = 'LOCALE_MATCHER_CHANGE';

export const TIME_ZONE_CHANGE = 'TIME_ZONE_CHANGE';

export const HOUR12_CHANGE = 'HOUR12_CHANGE';

export const HOUR_CYCLE_CHANGE = 'HOUR_CYCLE_CHANGE';

export const FORMAT_MATCHER_CHANGE = 'FORMAT_MATCHER_CHANGE';

export const WEEK_DAY_CHANGE = 'WEEK_DAY_CHANGE';

export const ERA_CHANGE = 'ERA_CHANGE';

export const YEAR_CHANGE = 'YEAR_CHANGE';

export const MONTH_CHANGE = 'MONTH_CHANGE';

export const DAY_CHANGE = 'DAY_CHANGE';

export const HOUR_CHANGE = 'HOUR_CHANGE';

export const MINUTE_CHANGE = 'MINUTE_CHANGE';

export const SECOND_CHANGE = 'SECOND_CHANGE';

export const TIME_ZONE_NAME_CHANGE = 'TIME_ZONE_NAME_CHANGE';
