export const LOCALE_CHANGE = 'LOCALE_CHANGE';

export const LOCALE_MATCHER_CHANGE = 'LOCALE_MATCHER_CHANGE';

export const TYPE_CHANGE = 'TYPE_CHANGE';

export const MINIMUM_INTEGER_DIGITS_CHANGE = 'MINIMUM_INTEGER_DIGITS_CHANGE';

export const MINIMUM_FRACTION_DIGITS_CHANGE = 'MINIMUM_FRACTION_DIGITS_CHANGE';

export const MAXIMUM_FRACTION_DIGITS_CHANGE = 'MAXIMUM_FRACTION_DIGITS_CHANGE';

export const MINIMUM_SIGNIFICANT_DIGITS_CHANGE =
  'MINIMUM_SIGNIFICANT_DIGITS_CHANGE';

export const MAXIMUM_SIGNIFICANT_DIGITS_CHANGE =
  'MAXIMUM_SIGNIFICANT_DIGITS_CHANGE';

export const RESET = 'RESET';
